import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "./Footer";
import Header from "./Header";

export const mplus_regular = M_PLUS_Rounded_1c({
  subsets: ["latin"],
  weight: "400",
});
export const mplus_bold = M_PLUS_Rounded_1c({
  subsets: ["latin"],
  weight: "700",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={mplus_regular.className}>
      <body className="text-foreground bg-light dark:bg-dark min-h-screen transition-colors place-items-center">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
